/**
 * Cheery Chow Recipe API
 * Nutrition and recipe nutrition management API.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: john@cheerychow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CheeryChowRecipeApi) {
      root.CheeryChowRecipeApi = {};
    }
    root.CheeryChowRecipeApi.Ingredient = factory(root.CheeryChowRecipeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Ingredient model module.
   * @module model/Ingredient
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>Ingredient</code>.
   * @alias module:model/Ingredient
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>Ingredient</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ingredient} obj Optional instance to populate.
   * @return {module:model/Ingredient} The populated <code>Ingredient</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('added')) {
        obj['added'] = ApiClient.convertToType(data['added'], 'Integer');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('amount_unit')) {
        obj['amount_unit'] = ApiClient.convertToType(data['amount_unit'], 'String');
      }
      if (data.hasOwnProperty('common_name')) {
        obj['common_name'] = ApiClient.convertToType(data['common_name'], 'String');
      }
      if (data.hasOwnProperty('food_id')) {
        obj['food_id'] = ApiClient.convertToType(data['food_id'], 'Integer');
      }
      if (data.hasOwnProperty('group_id')) {
        obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Integer');
      }
      if (data.hasOwnProperty('ingredient_id')) {
        obj['ingredient_id'] = ApiClient.convertToType(data['ingredient_id'], 'Integer');
      }
      if (data.hasOwnProperty('ingredient_line')) {
        obj['ingredient_line'] = ApiClient.convertToType(data['ingredient_line'], 'String');
      }
      if (data.hasOwnProperty('multiplier')) {
        obj['multiplier'] = ApiClient.convertToType(data['multiplier'], 'Integer');
      }
      if (data.hasOwnProperty('recipe_id')) {
        obj['recipe_id'] = ApiClient.convertToType(data['recipe_id'], 'Integer');
      }
      if (data.hasOwnProperty('result')) {
        obj['result'] = ApiClient.convertToType(data['result'], 'String');
      }
      if (data.hasOwnProperty('seq')) {
        obj['seq'] = ApiClient.convertToType(data['seq'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} added
   */
  exports.prototype['added'] = undefined;
  /**
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {String} amount_unit
   */
  exports.prototype['amount_unit'] = undefined;
  /**
   * @member {String} common_name
   */
  exports.prototype['common_name'] = undefined;
  /**
   * @member {Integer} food_id
   */
  exports.prototype['food_id'] = undefined;
  /**
   * @member {Integer} group_id
   */
  exports.prototype['group_id'] = undefined;
  /**
   * @member {Integer} ingredient_id
   */
  exports.prototype['ingredient_id'] = undefined;
  /**
   * @member {String} ingredient_line
   */
  exports.prototype['ingredient_line'] = undefined;
  /**
   * @member {Integer} multiplier
   */
  exports.prototype['multiplier'] = undefined;
  /**
   * @member {Integer} recipe_id
   */
  exports.prototype['recipe_id'] = undefined;
  /**
   * @member {String} result
   */
  exports.prototype['result'] = undefined;
  /**
   * @member {Integer} seq
   */
  exports.prototype['seq'] = undefined;



  return exports;
}));


