/**
 * Cheery Chow Recipe API
 * Nutrition and recipe nutrition management API.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: john@cheerychow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CheeryChowRecipeApi) {
      root.CheeryChowRecipeApi = {};
    }
    root.CheeryChowRecipeApi.MenuItem = factory(root.CheeryChowRecipeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MenuItem model module.
   * @module model/MenuItem
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>MenuItem</code>.
   * @alias module:model/MenuItem
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>MenuItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MenuItem} obj Optional instance to populate.
   * @return {module:model/MenuItem} The populated <code>MenuItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('group_id')) {
        obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Integer');
      }
      if (data.hasOwnProperty('item_description')) {
        obj['item_description'] = ApiClient.convertToType(data['item_description'], 'String');
      }
      if (data.hasOwnProperty('item_name')) {
        obj['item_name'] = ApiClient.convertToType(data['item_name'], 'String');
      }
      if (data.hasOwnProperty('item_position')) {
        obj['item_position'] = ApiClient.convertToType(data['item_position'], 'String');
      }
      if (data.hasOwnProperty('item_price')) {
        obj['item_price'] = ApiClient.convertToType(data['item_price'], 'Number');
      }
      if (data.hasOwnProperty('menu_item_id')) {
        obj['menu_item_id'] = ApiClient.convertToType(data['menu_item_id'], 'Integer');
      }
      if (data.hasOwnProperty('recipe_id')) {
        obj['recipe_id'] = ApiClient.convertToType(data['recipe_id'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} group_id
   */
  exports.prototype['group_id'] = undefined;
  /**
   * @member {String} item_description
   */
  exports.prototype['item_description'] = undefined;
  /**
   * @member {String} item_name
   */
  exports.prototype['item_name'] = undefined;
  /**
   * @member {String} item_position
   */
  exports.prototype['item_position'] = undefined;
  /**
   * @member {Number} item_price
   */
  exports.prototype['item_price'] = undefined;
  /**
   * @member {Integer} menu_item_id
   */
  exports.prototype['menu_item_id'] = undefined;
  /**
   * @member {Integer} recipe_id
   */
  exports.prototype['recipe_id'] = undefined;



  return exports;
}));


