/**
 * Cheery Chow Recipe API
 * Nutrition and recipe nutrition management API.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: john@cheerychow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CheeryChowRecipeApi) {
      root.CheeryChowRecipeApi = {};
    }
    root.CheeryChowRecipeApi.RDP = factory(root.CheeryChowRecipeApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RDP model module.
   * @module model/RDP
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>RDP</code>.
   * @alias module:model/RDP
   * @class
   */
  var exports = function() {
    var _this = this;







































































































  };

  /**
   * Constructs a <code>RDP</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RDP} obj Optional instance to populate.
   * @return {module:model/RDP} The populated <code>RDP</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('alpha_carot')) {
        obj['alpha_carot'] = ApiClient.convertToType(data['alpha_carot'], 'Integer');
      }
      if (data.hasOwnProperty('alpha_carot_unit')) {
        obj['alpha_carot_unit'] = ApiClient.convertToType(data['alpha_carot_unit'], 'String');
      }
      if (data.hasOwnProperty('beta_carot')) {
        obj['beta_carot'] = ApiClient.convertToType(data['beta_carot'], 'Integer');
      }
      if (data.hasOwnProperty('beta_carot_unit')) {
        obj['beta_carot_unit'] = ApiClient.convertToType(data['beta_carot_unit'], 'String');
      }
      if (data.hasOwnProperty('beta_crypt')) {
        obj['beta_crypt'] = ApiClient.convertToType(data['beta_crypt'], 'Integer');
      }
      if (data.hasOwnProperty('beta_crypt_unit')) {
        obj['beta_crypt_unit'] = ApiClient.convertToType(data['beta_crypt_unit'], 'String');
      }
      if (data.hasOwnProperty('biotin_unit')) {
        obj['biotin_unit'] = ApiClient.convertToType(data['biotin_unit'], 'String');
      }
      if (data.hasOwnProperty('bioton')) {
        obj['bioton'] = ApiClient.convertToType(data['bioton'], 'Integer');
      }
      if (data.hasOwnProperty('calcium')) {
        obj['calcium'] = ApiClient.convertToType(data['calcium'], 'Integer');
      }
      if (data.hasOwnProperty('calcium_unit')) {
        obj['calcium_unit'] = ApiClient.convertToType(data['calcium_unit'], 'String');
      }
      if (data.hasOwnProperty('calories')) {
        obj['calories'] = ApiClient.convertToType(data['calories'], 'Integer');
      }
      if (data.hasOwnProperty('calories_unit')) {
        obj['calories_unit'] = ApiClient.convertToType(data['calories_unit'], 'String');
      }
      if (data.hasOwnProperty('carbs')) {
        obj['carbs'] = ApiClient.convertToType(data['carbs'], 'Integer');
      }
      if (data.hasOwnProperty('carbs_unit')) {
        obj['carbs_unit'] = ApiClient.convertToType(data['carbs_unit'], 'String');
      }
      if (data.hasOwnProperty('chloride')) {
        obj['chloride'] = ApiClient.convertToType(data['chloride'], 'Integer');
      }
      if (data.hasOwnProperty('chloride_unit')) {
        obj['chloride_unit'] = ApiClient.convertToType(data['chloride_unit'], 'String');
      }
      if (data.hasOwnProperty('cholestrl')) {
        obj['cholestrl'] = ApiClient.convertToType(data['cholestrl'], 'Integer');
      }
      if (data.hasOwnProperty('cholestrl_unit')) {
        obj['cholestrl_unit'] = ApiClient.convertToType(data['cholestrl_unit'], 'String');
      }
      if (data.hasOwnProperty('choline_tot')) {
        obj['choline_tot'] = ApiClient.convertToType(data['choline_tot'], 'Integer');
      }
      if (data.hasOwnProperty('choline_tot_unit')) {
        obj['choline_tot_unit'] = ApiClient.convertToType(data['choline_tot_unit'], 'String');
      }
      if (data.hasOwnProperty('chromium')) {
        obj['chromium'] = ApiClient.convertToType(data['chromium'], 'Integer');
      }
      if (data.hasOwnProperty('chromium_unit')) {
        obj['chromium_unit'] = ApiClient.convertToType(data['chromium_unit'], 'String');
      }
      if (data.hasOwnProperty('copper')) {
        obj['copper'] = ApiClient.convertToType(data['copper'], 'Integer');
      }
      if (data.hasOwnProperty('copper_unit')) {
        obj['copper_unit'] = ApiClient.convertToType(data['copper_unit'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
      if (data.hasOwnProperty('fiber_td')) {
        obj['fiber_td'] = ApiClient.convertToType(data['fiber_td'], 'Integer');
      }
      if (data.hasOwnProperty('fiber_td_unit')) {
        obj['fiber_td_unit'] = ApiClient.convertToType(data['fiber_td_unit'], 'String');
      }
      if (data.hasOwnProperty('fluoride')) {
        obj['fluoride'] = ApiClient.convertToType(data['fluoride'], 'Integer');
      }
      if (data.hasOwnProperty('fluoride_unit')) {
        obj['fluoride_unit'] = ApiClient.convertToType(data['fluoride_unit'], 'String');
      }
      if (data.hasOwnProperty('folate_dfe')) {
        obj['folate_dfe'] = ApiClient.convertToType(data['folate_dfe'], 'Integer');
      }
      if (data.hasOwnProperty('folate_dfe_unit')) {
        obj['folate_dfe_unit'] = ApiClient.convertToType(data['folate_dfe_unit'], 'String');
      }
      if (data.hasOwnProperty('folate_tot')) {
        obj['folate_tot'] = ApiClient.convertToType(data['folate_tot'], 'Integer');
      }
      if (data.hasOwnProperty('folate_tot_unit')) {
        obj['folate_tot_unit'] = ApiClient.convertToType(data['folate_tot_unit'], 'String');
      }
      if (data.hasOwnProperty('folic_acid')) {
        obj['folic_acid'] = ApiClient.convertToType(data['folic_acid'], 'Integer');
      }
      if (data.hasOwnProperty('folic_acid_unit')) {
        obj['folic_acid_unit'] = ApiClient.convertToType(data['folic_acid_unit'], 'String');
      }
      if (data.hasOwnProperty('food_folate')) {
        obj['food_folate'] = ApiClient.convertToType(data['food_folate'], 'Integer');
      }
      if (data.hasOwnProperty('food_folate_unit')) {
        obj['food_folate_unit'] = ApiClient.convertToType(data['food_folate_unit'], 'String');
      }
      if (data.hasOwnProperty('gender')) {
        obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
      }
      if (data.hasOwnProperty('iodine')) {
        obj['iodine'] = ApiClient.convertToType(data['iodine'], 'Integer');
      }
      if (data.hasOwnProperty('iodine_unit')) {
        obj['iodine_unit'] = ApiClient.convertToType(data['iodine_unit'], 'String');
      }
      if (data.hasOwnProperty('iron')) {
        obj['iron'] = ApiClient.convertToType(data['iron'], 'Integer');
      }
      if (data.hasOwnProperty('iron_unit')) {
        obj['iron_unit'] = ApiClient.convertToType(data['iron_unit'], 'String');
      }
      if (data.hasOwnProperty('lut_zea')) {
        obj['lut_zea'] = ApiClient.convertToType(data['lut_zea'], 'Integer');
      }
      if (data.hasOwnProperty('lut_zea_unit')) {
        obj['lut_zea_unit'] = ApiClient.convertToType(data['lut_zea_unit'], 'String');
      }
      if (data.hasOwnProperty('lycopene')) {
        obj['lycopene'] = ApiClient.convertToType(data['lycopene'], 'Integer');
      }
      if (data.hasOwnProperty('lycopene_unit')) {
        obj['lycopene_unit'] = ApiClient.convertToType(data['lycopene_unit'], 'String');
      }
      if (data.hasOwnProperty('magnesium')) {
        obj['magnesium'] = ApiClient.convertToType(data['magnesium'], 'Integer');
      }
      if (data.hasOwnProperty('magnesium_unit')) {
        obj['magnesium_unit'] = ApiClient.convertToType(data['magnesium_unit'], 'String');
      }
      if (data.hasOwnProperty('manganese')) {
        obj['manganese'] = ApiClient.convertToType(data['manganese'], 'Integer');
      }
      if (data.hasOwnProperty('manganese_unit')) {
        obj['manganese_unit'] = ApiClient.convertToType(data['manganese_unit'], 'String');
      }
      if (data.hasOwnProperty('molybdenum')) {
        obj['molybdenum'] = ApiClient.convertToType(data['molybdenum'], 'Integer');
      }
      if (data.hasOwnProperty('molybdenum_unit')) {
        obj['molybdenum_unit'] = ApiClient.convertToType(data['molybdenum_unit'], 'String');
      }
      if (data.hasOwnProperty('mono_fat')) {
        obj['mono_fat'] = ApiClient.convertToType(data['mono_fat'], 'Integer');
      }
      if (data.hasOwnProperty('mono_fat_unit')) {
        obj['mono_fat_unit'] = ApiClient.convertToType(data['mono_fat_unit'], 'String');
      }
      if (data.hasOwnProperty('phosphorus')) {
        obj['phosphorus'] = ApiClient.convertToType(data['phosphorus'], 'Integer');
      }
      if (data.hasOwnProperty('phosphorus_unit')) {
        obj['phosphorus_unit'] = ApiClient.convertToType(data['phosphorus_unit'], 'String');
      }
      if (data.hasOwnProperty('poly_fat')) {
        obj['poly_fat'] = ApiClient.convertToType(data['poly_fat'], 'Integer');
      }
      if (data.hasOwnProperty('poly_fat_unit')) {
        obj['poly_fat_unit'] = ApiClient.convertToType(data['poly_fat_unit'], 'String');
      }
      if (data.hasOwnProperty('potassium')) {
        obj['potassium'] = ApiClient.convertToType(data['potassium'], 'Integer');
      }
      if (data.hasOwnProperty('potassium_unit')) {
        obj['potassium_unit'] = ApiClient.convertToType(data['potassium_unit'], 'String');
      }
      if (data.hasOwnProperty('protein')) {
        obj['protein'] = ApiClient.convertToType(data['protein'], 'Integer');
      }
      if (data.hasOwnProperty('protein_unit')) {
        obj['protein_unit'] = ApiClient.convertToType(data['protein_unit'], 'String');
      }
      if (data.hasOwnProperty('retinol')) {
        obj['retinol'] = ApiClient.convertToType(data['retinol'], 'Integer');
      }
      if (data.hasOwnProperty('retinol_unit')) {
        obj['retinol_unit'] = ApiClient.convertToType(data['retinol_unit'], 'String');
      }
      if (data.hasOwnProperty('sat_fat')) {
        obj['sat_fat'] = ApiClient.convertToType(data['sat_fat'], 'Integer');
      }
      if (data.hasOwnProperty('sat_fat_unit')) {
        obj['sat_fat_unit'] = ApiClient.convertToType(data['sat_fat_unit'], 'String');
      }
      if (data.hasOwnProperty('selenium')) {
        obj['selenium'] = ApiClient.convertToType(data['selenium'], 'Integer');
      }
      if (data.hasOwnProperty('selenium_unit')) {
        obj['selenium_unit'] = ApiClient.convertToType(data['selenium_unit'], 'String');
      }
      if (data.hasOwnProperty('sodium')) {
        obj['sodium'] = ApiClient.convertToType(data['sodium'], 'Integer');
      }
      if (data.hasOwnProperty('sodium_unit')) {
        obj['sodium_unit'] = ApiClient.convertToType(data['sodium_unit'], 'String');
      }
      if (data.hasOwnProperty('total_fat')) {
        obj['total_fat'] = ApiClient.convertToType(data['total_fat'], 'Integer');
      }
      if (data.hasOwnProperty('total_fat_unit')) {
        obj['total_fat_unit'] = ApiClient.convertToType(data['total_fat_unit'], 'String');
      }
      if (data.hasOwnProperty('total_sugar')) {
        obj['total_sugar'] = ApiClient.convertToType(data['total_sugar'], 'Integer');
      }
      if (data.hasOwnProperty('total_sugar_unit')) {
        obj['total_sugar_unit'] = ApiClient.convertToType(data['total_sugar_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_a_iu')) {
        obj['vit_a_iu'] = ApiClient.convertToType(data['vit_a_iu'], 'Integer');
      }
      if (data.hasOwnProperty('vit_a_iu_unit')) {
        obj['vit_a_iu_unit'] = ApiClient.convertToType(data['vit_a_iu_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_a_rae')) {
        obj['vit_a_rae'] = ApiClient.convertToType(data['vit_a_rae'], 'Integer');
      }
      if (data.hasOwnProperty('vit_a_rae_unit')) {
        obj['vit_a_rae_unit'] = ApiClient.convertToType(data['vit_a_rae_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_b1')) {
        obj['vit_b1'] = ApiClient.convertToType(data['vit_b1'], 'Integer');
      }
      if (data.hasOwnProperty('vit_b12')) {
        obj['vit_b12'] = ApiClient.convertToType(data['vit_b12'], 'Integer');
      }
      if (data.hasOwnProperty('vit_b12_unit')) {
        obj['vit_b12_unit'] = ApiClient.convertToType(data['vit_b12_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_b1_unit')) {
        obj['vit_b1_unit'] = ApiClient.convertToType(data['vit_b1_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_b2')) {
        obj['vit_b2'] = ApiClient.convertToType(data['vit_b2'], 'Integer');
      }
      if (data.hasOwnProperty('vit_b2_unit')) {
        obj['vit_b2_unit'] = ApiClient.convertToType(data['vit_b2_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_b3')) {
        obj['vit_b3'] = ApiClient.convertToType(data['vit_b3'], 'Integer');
      }
      if (data.hasOwnProperty('vit_b3_unit')) {
        obj['vit_b3_unit'] = ApiClient.convertToType(data['vit_b3_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_b5')) {
        obj['vit_b5'] = ApiClient.convertToType(data['vit_b5'], 'Integer');
      }
      if (data.hasOwnProperty('vit_b5_unit')) {
        obj['vit_b5_unit'] = ApiClient.convertToType(data['vit_b5_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_b6')) {
        obj['vit_b6'] = ApiClient.convertToType(data['vit_b6'], 'Integer');
      }
      if (data.hasOwnProperty('vit_b6_unit')) {
        obj['vit_b6_unit'] = ApiClient.convertToType(data['vit_b6_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_c')) {
        obj['vit_c'] = ApiClient.convertToType(data['vit_c'], 'Integer');
      }
      if (data.hasOwnProperty('vit_c_unit')) {
        obj['vit_c_unit'] = ApiClient.convertToType(data['vit_c_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_d_iu')) {
        obj['vit_d_iu'] = ApiClient.convertToType(data['vit_d_iu'], 'Integer');
      }
      if (data.hasOwnProperty('vit_d_mcg')) {
        obj['vit_d_mcg'] = ApiClient.convertToType(data['vit_d_mcg'], 'Integer');
      }
      if (data.hasOwnProperty('vit_d_mcg_unit')) {
        obj['vit_d_mcg_unit'] = ApiClient.convertToType(data['vit_d_mcg_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_e')) {
        obj['vit_e'] = ApiClient.convertToType(data['vit_e'], 'Integer');
      }
      if (data.hasOwnProperty('vit_e_unit')) {
        obj['vit_e_unit'] = ApiClient.convertToType(data['vit_e_unit'], 'String');
      }
      if (data.hasOwnProperty('vit_k')) {
        obj['vit_k'] = ApiClient.convertToType(data['vit_k'], 'Integer');
      }
      if (data.hasOwnProperty('vit_k_unit')) {
        obj['vit_k_unit'] = ApiClient.convertToType(data['vit_k_unit'], 'String');
      }
      if (data.hasOwnProperty('vivit_d_iu_unit')) {
        obj['vivit_d_iu_unit'] = ApiClient.convertToType(data['vivit_d_iu_unit'], 'String');
      }
      if (data.hasOwnProperty('zinc')) {
        obj['zinc'] = ApiClient.convertToType(data['zinc'], 'Integer');
      }
      if (data.hasOwnProperty('zinc_unit')) {
        obj['zinc_unit'] = ApiClient.convertToType(data['zinc_unit'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} alpha_carot
   */
  exports.prototype['alpha_carot'] = undefined;
  /**
   * @member {String} alpha_carot_unit
   */
  exports.prototype['alpha_carot_unit'] = undefined;
  /**
   * @member {Integer} beta_carot
   */
  exports.prototype['beta_carot'] = undefined;
  /**
   * @member {String} beta_carot_unit
   */
  exports.prototype['beta_carot_unit'] = undefined;
  /**
   * @member {Integer} beta_crypt
   */
  exports.prototype['beta_crypt'] = undefined;
  /**
   * @member {String} beta_crypt_unit
   */
  exports.prototype['beta_crypt_unit'] = undefined;
  /**
   * @member {String} biotin_unit
   */
  exports.prototype['biotin_unit'] = undefined;
  /**
   * @member {Integer} bioton
   */
  exports.prototype['bioton'] = undefined;
  /**
   * @member {Integer} calcium
   */
  exports.prototype['calcium'] = undefined;
  /**
   * @member {String} calcium_unit
   */
  exports.prototype['calcium_unit'] = undefined;
  /**
   * @member {Integer} calories
   */
  exports.prototype['calories'] = undefined;
  /**
   * @member {String} calories_unit
   */
  exports.prototype['calories_unit'] = undefined;
  /**
   * @member {Integer} carbs
   */
  exports.prototype['carbs'] = undefined;
  /**
   * @member {String} carbs_unit
   */
  exports.prototype['carbs_unit'] = undefined;
  /**
   * @member {Integer} chloride
   */
  exports.prototype['chloride'] = undefined;
  /**
   * @member {String} chloride_unit
   */
  exports.prototype['chloride_unit'] = undefined;
  /**
   * @member {Integer} cholestrl
   */
  exports.prototype['cholestrl'] = undefined;
  /**
   * @member {String} cholestrl_unit
   */
  exports.prototype['cholestrl_unit'] = undefined;
  /**
   * @member {Integer} choline_tot
   */
  exports.prototype['choline_tot'] = undefined;
  /**
   * @member {String} choline_tot_unit
   */
  exports.prototype['choline_tot_unit'] = undefined;
  /**
   * @member {Integer} chromium
   */
  exports.prototype['chromium'] = undefined;
  /**
   * @member {String} chromium_unit
   */
  exports.prototype['chromium_unit'] = undefined;
  /**
   * @member {Integer} copper
   */
  exports.prototype['copper'] = undefined;
  /**
   * @member {String} copper_unit
   */
  exports.prototype['copper_unit'] = undefined;
  /**
   * @member {String} country
   */
  exports.prototype['country'] = undefined;
  /**
   * @member {Integer} fiber_td
   */
  exports.prototype['fiber_td'] = undefined;
  /**
   * @member {String} fiber_td_unit
   */
  exports.prototype['fiber_td_unit'] = undefined;
  /**
   * @member {Integer} fluoride
   */
  exports.prototype['fluoride'] = undefined;
  /**
   * @member {String} fluoride_unit
   */
  exports.prototype['fluoride_unit'] = undefined;
  /**
   * @member {Integer} folate_dfe
   */
  exports.prototype['folate_dfe'] = undefined;
  /**
   * @member {String} folate_dfe_unit
   */
  exports.prototype['folate_dfe_unit'] = undefined;
  /**
   * @member {Integer} folate_tot
   */
  exports.prototype['folate_tot'] = undefined;
  /**
   * @member {String} folate_tot_unit
   */
  exports.prototype['folate_tot_unit'] = undefined;
  /**
   * @member {Integer} folic_acid
   */
  exports.prototype['folic_acid'] = undefined;
  /**
   * @member {String} folic_acid_unit
   */
  exports.prototype['folic_acid_unit'] = undefined;
  /**
   * @member {Integer} food_folate
   */
  exports.prototype['food_folate'] = undefined;
  /**
   * @member {String} food_folate_unit
   */
  exports.prototype['food_folate_unit'] = undefined;
  /**
   * @member {String} gender
   */
  exports.prototype['gender'] = undefined;
  /**
   * @member {Integer} iodine
   */
  exports.prototype['iodine'] = undefined;
  /**
   * @member {String} iodine_unit
   */
  exports.prototype['iodine_unit'] = undefined;
  /**
   * @member {Integer} iron
   */
  exports.prototype['iron'] = undefined;
  /**
   * @member {String} iron_unit
   */
  exports.prototype['iron_unit'] = undefined;
  /**
   * @member {Integer} lut_zea
   */
  exports.prototype['lut_zea'] = undefined;
  /**
   * @member {String} lut_zea_unit
   */
  exports.prototype['lut_zea_unit'] = undefined;
  /**
   * @member {Integer} lycopene
   */
  exports.prototype['lycopene'] = undefined;
  /**
   * @member {String} lycopene_unit
   */
  exports.prototype['lycopene_unit'] = undefined;
  /**
   * @member {Integer} magnesium
   */
  exports.prototype['magnesium'] = undefined;
  /**
   * @member {String} magnesium_unit
   */
  exports.prototype['magnesium_unit'] = undefined;
  /**
   * @member {Integer} manganese
   */
  exports.prototype['manganese'] = undefined;
  /**
   * @member {String} manganese_unit
   */
  exports.prototype['manganese_unit'] = undefined;
  /**
   * @member {Integer} molybdenum
   */
  exports.prototype['molybdenum'] = undefined;
  /**
   * @member {String} molybdenum_unit
   */
  exports.prototype['molybdenum_unit'] = undefined;
  /**
   * @member {Integer} mono_fat
   */
  exports.prototype['mono_fat'] = undefined;
  /**
   * @member {String} mono_fat_unit
   */
  exports.prototype['mono_fat_unit'] = undefined;
  /**
   * @member {Integer} phosphorus
   */
  exports.prototype['phosphorus'] = undefined;
  /**
   * @member {String} phosphorus_unit
   */
  exports.prototype['phosphorus_unit'] = undefined;
  /**
   * @member {Integer} poly_fat
   */
  exports.prototype['poly_fat'] = undefined;
  /**
   * @member {String} poly_fat_unit
   */
  exports.prototype['poly_fat_unit'] = undefined;
  /**
   * @member {Integer} potassium
   */
  exports.prototype['potassium'] = undefined;
  /**
   * @member {String} potassium_unit
   */
  exports.prototype['potassium_unit'] = undefined;
  /**
   * @member {Integer} protein
   */
  exports.prototype['protein'] = undefined;
  /**
   * @member {String} protein_unit
   */
  exports.prototype['protein_unit'] = undefined;
  /**
   * @member {Integer} retinol
   */
  exports.prototype['retinol'] = undefined;
  /**
   * @member {String} retinol_unit
   */
  exports.prototype['retinol_unit'] = undefined;
  /**
   * @member {Integer} sat_fat
   */
  exports.prototype['sat_fat'] = undefined;
  /**
   * @member {String} sat_fat_unit
   */
  exports.prototype['sat_fat_unit'] = undefined;
  /**
   * @member {Integer} selenium
   */
  exports.prototype['selenium'] = undefined;
  /**
   * @member {String} selenium_unit
   */
  exports.prototype['selenium_unit'] = undefined;
  /**
   * @member {Integer} sodium
   */
  exports.prototype['sodium'] = undefined;
  /**
   * @member {String} sodium_unit
   */
  exports.prototype['sodium_unit'] = undefined;
  /**
   * @member {Integer} total_fat
   */
  exports.prototype['total_fat'] = undefined;
  /**
   * @member {String} total_fat_unit
   */
  exports.prototype['total_fat_unit'] = undefined;
  /**
   * @member {Integer} total_sugar
   */
  exports.prototype['total_sugar'] = undefined;
  /**
   * @member {String} total_sugar_unit
   */
  exports.prototype['total_sugar_unit'] = undefined;
  /**
   * @member {Integer} vit_a_iu
   */
  exports.prototype['vit_a_iu'] = undefined;
  /**
   * @member {String} vit_a_iu_unit
   */
  exports.prototype['vit_a_iu_unit'] = undefined;
  /**
   * @member {Integer} vit_a_rae
   */
  exports.prototype['vit_a_rae'] = undefined;
  /**
   * @member {String} vit_a_rae_unit
   */
  exports.prototype['vit_a_rae_unit'] = undefined;
  /**
   * @member {Integer} vit_b1
   */
  exports.prototype['vit_b1'] = undefined;
  /**
   * @member {Integer} vit_b12
   */
  exports.prototype['vit_b12'] = undefined;
  /**
   * @member {String} vit_b12_unit
   */
  exports.prototype['vit_b12_unit'] = undefined;
  /**
   * @member {String} vit_b1_unit
   */
  exports.prototype['vit_b1_unit'] = undefined;
  /**
   * @member {Integer} vit_b2
   */
  exports.prototype['vit_b2'] = undefined;
  /**
   * @member {String} vit_b2_unit
   */
  exports.prototype['vit_b2_unit'] = undefined;
  /**
   * @member {Integer} vit_b3
   */
  exports.prototype['vit_b3'] = undefined;
  /**
   * @member {String} vit_b3_unit
   */
  exports.prototype['vit_b3_unit'] = undefined;
  /**
   * @member {Integer} vit_b5
   */
  exports.prototype['vit_b5'] = undefined;
  /**
   * @member {String} vit_b5_unit
   */
  exports.prototype['vit_b5_unit'] = undefined;
  /**
   * @member {Integer} vit_b6
   */
  exports.prototype['vit_b6'] = undefined;
  /**
   * @member {String} vit_b6_unit
   */
  exports.prototype['vit_b6_unit'] = undefined;
  /**
   * @member {Integer} vit_c
   */
  exports.prototype['vit_c'] = undefined;
  /**
   * @member {String} vit_c_unit
   */
  exports.prototype['vit_c_unit'] = undefined;
  /**
   * @member {Integer} vit_d_iu
   */
  exports.prototype['vit_d_iu'] = undefined;
  /**
   * @member {Integer} vit_d_mcg
   */
  exports.prototype['vit_d_mcg'] = undefined;
  /**
   * @member {String} vit_d_mcg_unit
   */
  exports.prototype['vit_d_mcg_unit'] = undefined;
  /**
   * @member {Integer} vit_e
   */
  exports.prototype['vit_e'] = undefined;
  /**
   * @member {String} vit_e_unit
   */
  exports.prototype['vit_e_unit'] = undefined;
  /**
   * @member {Integer} vit_k
   */
  exports.prototype['vit_k'] = undefined;
  /**
   * @member {String} vit_k_unit
   */
  exports.prototype['vit_k_unit'] = undefined;
  /**
   * @member {String} vivit_d_iu_unit
   */
  exports.prototype['vivit_d_iu_unit'] = undefined;
  /**
   * @member {Integer} zinc
   */
  exports.prototype['zinc'] = undefined;
  /**
   * @member {String} zinc_unit
   */
  exports.prototype['zinc_unit'] = undefined;



  return exports;
}));


