/**
 * Cheery Chow Recipe API
 * Nutrition and recipe nutrition management API.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: john@cheerychow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HttpAPIError', 'model/AbbrevWithProvides', 'model/NutritionAbbrev'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HttpAPIError'), require('../model/AbbrevWithProvides'), require('../model/NutritionAbbrev'));
  } else {
    // Browser globals (root is window)
    if (!root.CheeryChowRecipeApi) {
      root.CheeryChowRecipeApi = {};
    }
    root.CheeryChowRecipeApi.FoodnutritionApi = factory(root.CheeryChowRecipeApi.ApiClient, root.CheeryChowRecipeApi.HttpAPIError, root.CheeryChowRecipeApi.AbbrevWithProvides, root.CheeryChowRecipeApi.NutritionAbbrev);
  }
}(this, function(ApiClient, HttpAPIError, AbbrevWithProvides, NutritionAbbrev) {
  'use strict';

  /**
   * Foodnutrition service.
   * @module api/FoodnutritionApi
   * @version 0.0.2
   */

  /**
   * Constructs a new FoodnutritionApi. 
   * @alias module:api/FoodnutritionApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the listAbbrevByFoodWithProvides operation.
     * @callback module:api/FoodnutritionApi~listAbbrevByFoodWithProvidesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AbbrevWithProvides} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves the nutrition for a particular food.
     * @param {Integer} foodId The id for the food to be fetched
     * @param {Number} amount Adjust the nutrition amount to per &#39;amount&#39; grams. If you want to know the nutritional content in 200g of a particular food, then enter it here as 200.
     * @param {String} rdacountry The country RDA to be used when calculating the RDA provided by the food.
     * @param {Object} opts Optional parameters
     * @param {String} opts.sortby The nutrition field to sort by. (default to calories)
     * @param {String} opts.sortdir The sort direction for the results. (default to desc)
     * @param {module:api/FoodnutritionApi~listAbbrevByFoodWithProvidesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AbbrevWithProvides}
     */
    this.listAbbrevByFoodWithProvides = function(foodId, amount, rdacountry, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'foodId' is set
      if (foodId == undefined || foodId == null) {
        throw "Missing the required parameter 'foodId' when calling listAbbrevByFoodWithProvides";
      }

      // verify the required parameter 'amount' is set
      if (amount == undefined || amount == null) {
        throw "Missing the required parameter 'amount' when calling listAbbrevByFoodWithProvides";
      }

      // verify the required parameter 'rdacountry' is set
      if (rdacountry == undefined || rdacountry == null) {
        throw "Missing the required parameter 'rdacountry' when calling listAbbrevByFoodWithProvides";
      }


      var pathParams = {
        'foodId': foodId,
        'amount': amount
      };
      var queryParams = {
        'rdacountry': rdacountry,
        'sortby': opts['sortby'],
        'sortdir': opts['sortdir']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AbbrevWithProvides;

      return this.apiClient.callApi(
        '/food-nutrition/by-food/{foodId}/{amount}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the showNutritionForAFood operation.
     * @callback module:api/FoodnutritionApi~showNutritionForAFoodCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NutritionAbbrev} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves the nutrition present in a particular food, present in &#39;amount&#39; grams of the food.
     * @param {Integer} foodId Food ID
     * @param {Number} amount The amount of food in grams
     * @param {module:api/FoodnutritionApi~showNutritionForAFoodCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NutritionAbbrev}
     */
    this.showNutritionForAFood = function(foodId, amount, callback) {
      var postBody = null;

      // verify the required parameter 'foodId' is set
      if (foodId == undefined || foodId == null) {
        throw "Missing the required parameter 'foodId' when calling showNutritionForAFood";
      }

      // verify the required parameter 'amount' is set
      if (amount == undefined || amount == null) {
        throw "Missing the required parameter 'amount' when calling showNutritionForAFood";
      }


      var pathParams = {
        'food_id': foodId,
        'amount': amount
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = NutritionAbbrev;

      return this.apiClient.callApi(
        '/food-nutrition/food/{food_id}/{amount}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
