/**
 * Cheery Chow Recipe API
 * Nutrition and recipe nutrition management API.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: john@cheerychow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HttpAPIError', 'model/RDA'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HttpAPIError'), require('../model/RDA'));
  } else {
    // Browser globals (root is window)
    if (!root.CheeryChowRecipeApi) {
      root.CheeryChowRecipeApi = {};
    }
    root.CheeryChowRecipeApi.RdaApi = factory(root.CheeryChowRecipeApi.ApiClient, root.CheeryChowRecipeApi.HttpAPIError, root.CheeryChowRecipeApi.RDA);
  }
}(this, function(ApiClient, HttpAPIError, RDA) {
  'use strict';

  /**
   * Rda service.
   * @module api/RdaApi
   * @version 0.0.2
   */

  /**
   * Constructs a new RdaApi. 
   * @alias module:api/RdaApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getRDAData operation.
     * @callback module:api/RdaApi~getRDADataCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RDA} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the rating for a recipe, by it&#39;s id
     * @param {String} country The country code which the RDA should reflect.
     * @param {String} gender The gender for which the RDA should apply.
     * @param {module:api/RdaApi~getRDADataCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RDA}
     */
    this.getRDAData = function(country, gender, callback) {
      var postBody = null;

      // verify the required parameter 'country' is set
      if (country == undefined || country == null) {
        throw "Missing the required parameter 'country' when calling getRDAData";
      }

      // verify the required parameter 'gender' is set
      if (gender == undefined || gender == null) {
        throw "Missing the required parameter 'gender' when calling getRDAData";
      }


      var pathParams = {
        'country': country,
        'gender': gender
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = RDA;

      return this.apiClient.callApi(
        '/rda/{country}/{gender}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
