/**
 * Cheery Chow Recipe API
 * Nutrition and recipe nutrition management API.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: john@cheerychow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CheeryChowRecipeApi);
  }
}(this, function(expect, CheeryChowRecipeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CheeryChowRecipeApi.ApplicationFood();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApplicationFood', function() {
    it('should create an instance of ApplicationFood', function() {
      // uncomment below and update the code to test ApplicationFood
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be.a(CheeryChowRecipeApi.ApplicationFood);
    });

    it('should have the property regexId (base name: "regex_id")', function() {
      // uncomment below and update the code to test the property regexId
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property foodId (base name: "food_id")', function() {
      // uncomment below and update the code to test the property foodId
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "group_id")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property regex (base name: "regex")', function() {
      // uncomment below and update the code to test the property regex
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property commonName (base name: "common_name")', function() {
      // uncomment below and update the code to test the property commonName
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property inUsda (base name: "in_usda")', function() {
      // uncomment below and update the code to test the property inUsda
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property highGenerality (base name: "high_generality")', function() {
      // uncomment below and update the code to test the property highGenerality
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property priority (base name: "priority")', function() {
      // uncomment below and update the code to test the property priority
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property defaultAmount (base name: "default_amount")', function() {
      // uncomment below and update the code to test the property defaultAmount
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property zeroCal (base name: "zero_cal")', function() {
      // uncomment below and update the code to test the property zeroCal
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property alcohol (base name: "alcohol")', function() {
      // uncomment below and update the code to test the property alcohol
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property meat (base name: "meat")', function() {
      // uncomment below and update the code to test the property meat
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property nut (base name: "nut")', function() {
      // uncomment below and update the code to test the property nut
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property egg (base name: "egg")', function() {
      // uncomment below and update the code to test the property egg
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property sugar (base name: "sugar")', function() {
      // uncomment below and update the code to test the property sugar
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property vegan (base name: "vegan")', function() {
      // uncomment below and update the code to test the property vegan
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property veg (base name: "veg")', function() {
      // uncomment below and update the code to test the property veg
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property glutenFree (base name: "gluten_free")', function() {
      // uncomment below and update the code to test the property glutenFree
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property fish (base name: "Fish")', function() {
      // uncomment below and update the code to test the property fish
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property unitsRegex (base name: "units_regex")', function() {
      // uncomment below and update the code to test the property unitsRegex
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

    it('should have the property tempHits (base name: "temp_hits")', function() {
      // uncomment below and update the code to test the property tempHits
      //var instane = new CheeryChowRecipeApi.ApplicationFood();
      //expect(instance).to.be();
    });

  });

}));
