/**
 * Cheery Chow Recipe API
 * Nutrition and recipe nutrition management API.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: john@cheerychow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CheeryChowRecipeApi);
  }
}(this, function(expect, CheeryChowRecipeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CheeryChowRecipeApi.FoodDes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FoodDes', function() {
    it('should create an instance of FoodDes', function() {
      // uncomment below and update the code to test FoodDes
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be.a(CheeryChowRecipeApi.FoodDes);
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property choFactor (base name: "cho_factor")', function() {
      // uncomment below and update the code to test the property choFactor
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property commonName (base name: "common_name")', function() {
      // uncomment below and update the code to test the property commonName
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property fatFactor (base name: "fat_factor")', function() {
      // uncomment below and update the code to test the property fatFactor
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property foodId (base name: "food_id")', function() {
      // uncomment below and update the code to test the property foodId
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property manufacturer (base name: "manufacturer")', function() {
      // uncomment below and update the code to test the property manufacturer
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property nFactor (base name: "n_factor")', function() {
      // uncomment below and update the code to test the property nFactor
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property proFactor (base name: "pro_factor")', function() {
      // uncomment below and update the code to test the property proFactor
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property refDesc (base name: "ref_desc")', function() {
      // uncomment below and update the code to test the property refDesc
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property refuse (base name: "refuse")', function() {
      // uncomment below and update the code to test the property refuse
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property sciname (base name: "sciname")', function() {
      // uncomment below and update the code to test the property sciname
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property shrtDesc (base name: "shrt_desc")', function() {
      // uncomment below and update the code to test the property shrtDesc
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

    it('should have the property survey (base name: "survey")', function() {
      // uncomment below and update the code to test the property survey
      //var instane = new CheeryChowRecipeApi.FoodDes();
      //expect(instance).to.be();
    });

  });

}));
